import { CatalogAnime } from "@/lib/types";

export const SEED_CATALOG: CatalogAnime[] = [
  {
    id: 1,
    title: "Attack on Titan",
    genres: ["Action", "Drama", "Mystery"],
    tone: ["Dark", "Intense", "Psychological"],
    synopsis: "Humanity fights for survival while uncovering conspiracies and moral collapse.",
    episodes: 89,
    popularity: 98,
    complexity: 9,
    morality: 9,
    emotionalIntensity: 9,
    posterGradient: "linear-gradient(160deg, #1f2937 0%, #7f1d1d 100%)",
  },
  {
    id: 2,
    title: "Steins;Gate",
    genres: ["Sci-Fi", "Thriller", "Drama"],
    tone: ["Emotional", "Suspenseful", "Mind-bending"],
    synopsis: "A group of friends accidentally manipulates time and pays the price.",
    episodes: 24,
    popularity: 89,
    complexity: 10,
    morality: 7,
    emotionalIntensity: 8,
    posterGradient: "linear-gradient(160deg, #312e81 0%, #0f172a 100%)",
  },
  {
    id: 3,
    title: "Frieren: Beyond Journey's End",
    genres: ["Fantasy", "Adventure", "Drama"],
    tone: ["Melancholic", "Wholesome", "Reflective"],
    synopsis: "An elf mage learns what life and connection mean after the hero's journey.",
    episodes: 28,
    popularity: 88,
    complexity: 7,
    morality: 6,
    emotionalIntensity: 8,
    posterGradient: "linear-gradient(160deg, #065f46 0%, #1e293b 100%)",
  },
  {
    id: 4,
    title: "Psycho-Pass",
    genres: ["Cyberpunk", "Thriller", "Crime"],
    tone: ["Dark", "Psychological", "Bleak"],
    synopsis: "Inspectors navigate a society where justice is pre-calculated by AI.",
    episodes: 41,
    popularity: 74,
    complexity: 8,
    morality: 10,
    emotionalIntensity: 7,
    posterGradient: "linear-gradient(160deg, #0f172a 0%, #4c1d95 100%)",
  },
  {
    id: 5,
    title: "Mob Psycho 100",
    genres: ["Action", "Comedy", "Supernatural"],
    tone: ["Chaotic", "Heartfelt", "Hopeful"],
    synopsis: "A powerful psychic teen grows emotionally while facing bizarre threats.",
    episodes: 37,
    popularity: 79,
    complexity: 6,
    morality: 5,
    emotionalIntensity: 6,
    posterGradient: "linear-gradient(160deg, #4c1d95 0%, #db2777 100%)",
  },
  {
    id: 6,
    title: "March Comes in Like a Lion",
    genres: ["Drama", "Slice of Life"],
    tone: ["Sad", "Warm", "Healing"],
    synopsis: "A young shogi prodigy battles loneliness and slowly rebuilds belonging.",
    episodes: 44,
    popularity: 58,
    complexity: 7,
    morality: 5,
    emotionalIntensity: 9,
    posterGradient: "linear-gradient(160deg, #0c4a6e 0%, #7c3aed 100%)",
  },
  {
    id: 7,
    title: "Vinland Saga",
    genres: ["Action", "Historical", "Drama"],
    tone: ["Brutal", "Reflective", "Character-driven"],
    synopsis: "A warrior's revenge arc transforms into a search for meaning and peace.",
    episodes: 48,
    popularity: 86,
    complexity: 8,
    morality: 8,
    emotionalIntensity: 8,
    posterGradient: "linear-gradient(160deg, #78350f 0%, #111827 100%)",
  },
  {
    id: 8,
    title: "Land of the Lustrous",
    genres: ["Fantasy", "Mystery", "Psychological"],
    tone: ["Ethereal", "Melancholic", "Philosophical"],
    synopsis: "Gem-like beings fight for survival while one searches for identity.",
    episodes: 12,
    popularity: 52,
    complexity: 8,
    morality: 6,
    emotionalIntensity: 7,
    posterGradient: "linear-gradient(160deg, #0369a1 0%, #312e81 100%)",
  },
  {
    id: 9,
    title: "Haikyuu!!",
    genres: ["Sports", "Comedy", "Drama"],
    tone: ["High-energy", "Motivational", "Wholesome"],
    synopsis: "Underdog volleyball players push beyond limits through teamwork and grit.",
    episodes: 85,
    popularity: 90,
    complexity: 5,
    morality: 4,
    emotionalIntensity: 7,
    posterGradient: "linear-gradient(160deg, #ea580c 0%, #1e293b 100%)",
  },
  {
    id: 10,
    title: "Odd Taxi",
    genres: ["Mystery", "Crime", "Drama"],
    tone: ["Quirky", "Noir", "Psychological"],
    synopsis: "A taxi driver gets tangled in a layered conspiracy in a city of secrets.",
    episodes: 13,
    popularity: 49,
    complexity: 8,
    morality: 7,
    emotionalIntensity: 6,
    posterGradient: "linear-gradient(160deg, #334155 0%, #be185d 100%)",
  },
  {
    id: 11,
    title: "Blue Lock",
    genres: ["Sports", "Action", "Thriller"],
    tone: ["Competitive", "Aggressive", "High-energy"],
    synopsis: "Elite strikers compete in an ego-driven program to create the ultimate forward.",
    episodes: 24,
    popularity: 83,
    complexity: 5,
    morality: 6,
    emotionalIntensity: 8,
    posterGradient: "linear-gradient(160deg, #0f172a 0%, #1d4ed8 100%)",
  },
  {
    id: 12,
    title: "Natsume's Book of Friends",
    genres: ["Slice of Life", "Fantasy", "Supernatural"],
    tone: ["Soothing", "Bittersweet", "Wholesome"],
    synopsis: "A boy who sees spirits helps both humans and yokai resolve old bonds.",
    episodes: 74,
    popularity: 46,
    complexity: 6,
    morality: 4,
    emotionalIntensity: 7,
    posterGradient: "linear-gradient(160deg, #166534 0%, #1f2937 100%)",
  },
];

export const DEFAULT_WATCHLIST = [
  { animeId: 1, status: "Watching", progress: 18, rating: null, review: "" },
  { animeId: 3, status: "Completed", progress: 28, rating: 10, review: "Beautiful, reflective, and deeply emotional." },
  { animeId: 9, status: "Plan-to-Watch", progress: 0, rating: null, review: "" },
] as const;
